name: Coverage
on:
  push:
    branches:
      - main
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run coverage
        run: |
          coverage run --source=src/domain --omit='*/interface.py' -m unittest
      - name: Generate badge
        run: |
          coverage-badge -fo imgs/badge-coverage.svg
      - name: Commit report
        run: |
          git config --global user.name 'Breno Aquino GithubActions'
          git config --global user.email 'brenoaquino@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/charles-eyes-ba/video-processing-unit.git
          git checkout "${GITHUB_REF:11}"
          git add imgs/badge-coverage.svg
          git commit -m "[GithubActions] Update coverage badge" || echo "No changes to commit"
          git push